In [1]:
#https://www.codespeedy.com/vector-addition-and-subtraction-in-python/

import numpy as NP
A = [4, 7, 5]
B = [8, -4, 7]
print("The input arrays are :\n","A:",A ,"\n","B:",B)
Res= NP.add(A,B)
print("After addition the resulting array is :",Res)

The input arrays are :
 A: [4, 7, 5] 
 B: [8, -4, 7]
After addition the resulting array is : [12  3 12]


In [ ]:
import numpy as NP
A = [4, 8, 7] 
B = [5, -4, 8] 
print("The input arrays are :\n","A:",A ,"\n","B:",B)
Res1= NP.add(A,B)
Res2= NP.subtract(A,B) 
print("Result of Addition is :",Res1,"\n","Result of Subtraction is:",Res2)

The input arrays are :
 A: [4, 8, 7] 
 B: [5, -4, 8]
Result of Addition is : [ 9  4 15] 
 Result of Subtraction is: [-1 12 -1]


In [ ]:
# create a vector
from numpy import array
v = array([1, 2, 3])
print(v)

[1 2 3]


In [ ]:
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([1, 2, 3])
print(b)
c = a + b
print(c)

[1 2 3]
[1 2 3]
[2 4 6]


In [ ]:
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([0.5, 0.5, 0.5])
print(b)
c = a - b
print(c)

[1 2 3]
[0.5 0.5 0.5]
[0.5 1.5 2.5]


In [ ]:
# multiply vectors
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([1, 2, 3])
print(b)
c = a * b
print(c)

[1 2 3]
[1 2 3]
[1 4 9]


In [ ]:
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([1, 2, 3])
print(b)
c = a / b
print(c)

[1 2 3]
[1 2 3]
[1. 1. 1.]


In [ ]:

# dot product vectors
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([1, 2, 3])
print(b)
c = a.dot(b)
print(c)

[1 2 3]
[1 2 3]
14


In [ ]:

# VECTOR AND SCALAR
from numpy import array
a = array([1, 2, 3])
print(a)
s = 0.6
print(s)
c = s * a
print(c)

[1 2 3]
0.6
[0.6 1.2 1.8]
